import { useState } from 'react'
import { Button } from './ui/button'
import { count, money, type NodeRecord, type Report } from '../contract'
import type { RouteEvidence } from '../optional-contract'
const metricNames:Record<string,string>={in_degree:'Входящие связи',out_degree:'Исходящие связи',in_sum:'Входящая сумма',out_sum:'Исходящая сумма',incoming_tx_count:'Входящие переводы',outgoing_tx_count:'Исходящие переводы',near_cutoff_share:'Доля наблюдаемых переводов 5–10 тыс. ₸'}
export function Anomalies({node}:{node:NodeRecord}) {
 return <details className="inspector-details"><summary>Необычно для колена {node.anomalies?.length?`· ${node.anomalies.length}`:''}</summary><section>{node.anomalies===undefined?<p className="muted">В этом отчёте сравнение с коленом не рассчитано.</p>:!node.anomalies.length?<p className="muted">Сравнение выполнено: отклонения по правилам не отмечены.</p>:node.anomalies.map((a,i)=><div className="anomaly-item" key={i}><h3>{metricNames[a.metric]??a.metric}</h3><dl className="evidence-values"><div><dt>Наблюдение</dt><dd>{a.metric.includes('sum')?money(a.value):a.metric==='near_cutoff_share'?`${(a.value*100).toFixed(1)}%`:count(a.value)}</dd></div><div><dt>Медиана колена</dt><dd>{a.metric.includes('sum')?money(a.peer_median):a.metric==='near_cutoff_share'?`${(a.peer_median*100).toFixed(1)}%`:count(a.peer_median)}</dd></div></dl><p className="muted">Глубина {a.peer_depth} · {a.peer_n} участников сравнения, без текущего узла.</p><p className="small">{a.deviation===null?'MAD равен нулю: используется эмпирический ранг.':`Отклонение: ${a.deviation.toFixed(2)} по нормированной MAD.`}</p><details><summary>Правило расчёта</summary><p>{a.method}</p></details>{a.limitations.map((text,j)=><p className="evidence-limit" key={j}>{text}</p>)}</div>)}</section></details>
}
function RouteRow({route,cycle,onSelect}:{route:RouteEvidence;cycle:boolean;onSelect:(id:string)=>void}) {
 return <article className="route-row"><div className="route-gids">{[...route.gids,...(cycle?[route.gids[0]]:[])].map((gid,i)=><span key={`${gid}-${i}`}>{i>0&&<span className="muted">→</span>}<button onClick={()=>onSelect(gid)}>{gid}</button></span>)}</div><div className="route-labels"><span>{cycle?'Возвратный контур':'Два последовательных ребра'}</span>{route.repeated&&<span>Повторяется по датам</span>}</div><details><summary>Суммы и наблюдаемый порядок дат</summary><div className="route-legs">{route.legs.map((leg,i)=><div key={i}><span>{leg.src} → {leg.dst}</span><strong>{money(leg.sum_kzt)}</strong><small>{count(leg.n_tx)} переводов</small></div>)}</div><p>Дней начала со строгим порядком: {route.strict_episode_days}</p>{route.strict_date_examples.map((ex,i)=><p key={i}>Даты по порядку: {ex.dates.join(' → ')}</p>)}{route.same_day_ambiguous_examples.map((ex,i)=><p key={i}>Порядок внутри дня неизвестен: {ex.dates.join(' → ')}</p>)}{route.date_search_truncated&&<p className="evidence-limit">Поиск дат ограничен: повторяемость может быть неполной.</p>}{route.limitations.map((line,i)=><p className="evidence-limit" key={i}>{line}</p>)}</details></article>
}
export function RoutesPanel({report,gid,onSelect}:{report:Report;gid:string;onSelect:(id:string)=>void}) {
 const routes=report.routes,paths=routes?.paths.filter(r=>r.gids.includes(gid))??[],cycles=routes?.cycles.filter(r=>r.gids.includes(gid))??[]
 const [kind,setKind]=useState<'paths'|'cycles'>('paths'),[limit,setLimit]=useState(10)
 const rows=kind==='paths'?paths:cycles
 return <section className="analysis-panel"><div className="panel-heading"><div><div className="eyebrow">ПРОВЕРКА ГИПОТЕЗ</div><h2>Маршруты и возвраты</h2></div></div><div className="analysis-body"><p className="section-lead">Последовательность связей вокруг выбранного участника. Она не доказывает движение одних и тех же денег.</p>{!routes?<p className="empty-evidence">В этом отчёте маршруты не рассчитаны.</p>:<><div className="workspace-tabs"><Button variant={kind==='paths'?'secondary':'ghost'} onClick={()=>{setKind('paths');setLimit(10)}}>Маршруты · {paths.length}</Button><Button variant={kind==='cycles'?'secondary':'ghost'} onClick={()=>{setKind('cycles');setLimit(10)}}>Возвраты · {cycles.length}</Button></div>{routes.truncated_nodes.includes(gid)&&<p className="evidence-limit">Перечень ограничен бюджетом поиска. Отсутствие маршрута в списке не означает его отсутствия.</p>}{!rows.length?<p className="empty-evidence">Для участника такие связи в пределах поиска не найдены.</p>:rows.slice(0,limit).map((r,i)=><RouteRow key={`${kind}-${i}`} route={r} cycle={kind==='cycles'} onSelect={onSelect}/>)}{rows.length>limit&&<Button variant="outline" onClick={()=>setLimit(v=>v+10)}>Показать ещё маршруты</Button>}</>}</div></section>
}
export function ResiliencePanel({report,onSelect}:{report:Report;onSelect:(id:string)=>void}) {
 const [n,setN]=useState(0),data=report.resilience
 if(!data)return <section className="analysis-panel analysis-body"><h2>Сценарий изъятия</h2><p className="empty-evidence">В этом отчёте устойчивость сети не рассчитана.</p></section>
 const scenario=data.scenarios.find(s=>s.n_removed===n)??data.scenarios[0],base=data.baseline
 const rows:[string,string,string][]=[['Участники',count(base.n_nodes),count(scenario.n_nodes)],['Слабые компоненты',count(base.n_weak_components),count(scenario.n_weak_components)],['Крупнейшая компонента',count(base.largest_component_nodes),count(scenario.largest_component_nodes)],['Изоляты',count(base.n_isolates),count(scenario.n_isolates)],['Доля от оставшихся',`${(base.largest_share_surviving*100).toFixed(1)}%`,`${(scenario.largest_share_surviving*100).toFixed(1)}%`],['Доля от исходной сети',`${(base.largest_share_original*100).toFixed(1)}%`,`${(scenario.largest_share_original*100).toFixed(1)}%`]]
 return <section className="analysis-panel"><div className="panel-heading"><div><div className="eyebrow">СТРУКТУРНЫЙ ЭКСПЕРИМЕНТ</div><h2>Сценарий изъятия</h2></div></div><div className="analysis-body"><p className="section-lead">Как изменится связность, если исключить первых N участников рейтинга. Порядок фиксирован; роли и исходный граф остаются прежними.</p><label className="scenario-control">Убрать участников <select aria-label="Число удаляемых участников" value={n} onChange={e=>setN(Number(e.target.value))}>{data.scenarios.map(s=><option key={s.n_removed} value={s.n_removed}>{s.n_removed}</option>)}</select></label><table className="data-table"><thead><tr><th>Показатель</th><th className="numeric">Исходная сеть</th><th className="numeric">После сценария</th></tr></thead><tbody>{rows.map(([label,before,after])=><tr key={label}><td>{label}</td><td className="numeric">{before}</td><td className="numeric">{after}</td></tr>)}</tbody></table><p className="muted">Знаменатели: исходная сеть — {base.n_nodes}; оставшиеся — {scenario.n_nodes}. При отсутствии оставшихся узлов доля равна 0.</p><h3 className="removed-heading">Исключённые участники · {scenario.removed_gids.length}</h3><div className="removed-gids">{scenario.removed_gids.length?scenario.removed_gids.map(id=><button key={id} onClick={()=>onSelect(id)}>{id}</button>):<p className="muted">N = 0: исходная сеть без изменений.</p>}</div><p className="evidence-limit">Модель связности, а не прогноз пресечения операций. Реальные участники могут менять поведение.</p></div></section>
}
