import { useEffect, useState } from 'react'
import { Button } from './ui/button'
import type { Report } from '../contract'
type Reply={answer:string;citations:{gid:string;kind:string;reference:string}[];limitations:string[]}
export default function Assistant({gid,report,onSelect}:{gid:string;report:Report;onSelect:(id:string)=>void}) {
 const [status,setStatus]=useState<{status:string;message:string;provider?:string}|null>(null),[question,setQuestion]=useState(''),[reply,setReply]=useState<Reply|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const controller=new AbortController();fetch('/api/assistant/status',{signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(setStatus).catch(()=>{if(!controller.signal.aborted)setStatus({status:'unavailable',message:'AI-ассистент не подключён. Все расчёты доступны локально.'})});return()=>controller.abort()},[])
 async function ask(){setBusy(true);setError('');setReply(null);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),22000);try{const res=await fetch('/api/assistant/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,selected_gid:gid}),signal:controller.signal});const data=await res.json();if(!res.ok)throw new Error(data.error||'Не удалось получить ответ.');if(typeof data.answer!=='string'||!Array.isArray(data.citations)||!data.citations.length||!data.citations.every((c:Reply['citations'][number])=>typeof c.reference==='string'&&report.nodes.some(n=>n.gid===c.gid))||!Array.isArray(data.limitations))throw new Error('Нет проверяемых ссылок для ответа. Уточните вопрос.');setReply(data)}catch(e){setError(e instanceof Error&&e.name==='AbortError'?'Время ожидания истекло. Повторите запрос.':e instanceof Error?e.message:'Не удалось получить ответ.')}finally{clearTimeout(timer);setBusy(false)}}
 return <section className="analysis-panel assistant-panel"><div className="panel-heading"><div><div className="eyebrow">ВОПРОСЫ К ДАННЫМ</div><h2>Ассистент аналитика</h2></div></div><div className="analysis-body">{!status?<p role="status">Проверяем подключение…</p>:status.status!=='ready'?<p className="empty-evidence">{status.message}</p>:<><p className="section-lead">Ответы с проверяемыми ссылками на расчёт. Контекст: <span className="mono">{gid}</span>.</p>{status.provider==='remote'&&<p className="evidence-limit">Подключён внешний провайдер. Вопрос и ограниченные фрагменты отчёта передаются ему при отправке.</p>}<form onSubmit={e=>{e.preventDefault();void ask()}}><label htmlFor="assistant-question">Вопрос по наблюдаемым данным</label><textarea id="assistant-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} placeholder="Почему этот участник в приоритетах?" disabled={busy}/><Button type="submit" disabled={busy||!question.trim()}>{busy?'Проверяем свидетельства…':'Задать вопрос'}</Button></form>{busy&&<p role="status" className="muted">Запрос ограничен 20 секундами.</p>}{error&&<p role="alert" className="evidence-limit">{error}</p>}{reply&&<div className="assistant-reply"><h3>Наблюдения из отчёта</h3><p>{reply.answer}</p><h3>Проверить источники</h3><div className="citation-list">{reply.citations.map((c,i)=><button key={i} onClick={()=>onSelect(c.gid)}><span>{c.gid}</span><small>{c.reference}</small></button>)}</div><h3>Ограничения</h3>{reply.limitations.map((text,i)=><p key={i}>{text}</p>)}<p className="muted">Интерпретация требует проверки аналитиком. Неизвестные сведения не дополняются предположениями.</p></div>}</>}</div></section>
}
