import { ArrowRight, X } from 'lucide-react'
import { Button } from './ui/button'
import { money, count, type EdgeRecord, type Report } from '../contract'
export function EdgeDetail({edge,onClose,onSelect}:{edge:EdgeRecord;onClose:()=>void;onSelect:(id:string)=>void}) {
 return <section className="edge-detail" aria-label="Данные выбранной связи"><div className="edge-detail-top"><span className="eyebrow">ВЫБРАННАЯ СВЯЗЬ</span><Button variant="ghost" size="icon" onClick={onClose} aria-label="Закрыть данные связи"><X size={16}/></Button></div><strong className="edge-total">{money(edge.sum_kzt)}</strong><div className="edge-parties"><button onClick={()=>onSelect(edge.src)}><small>Отправитель</small>{edge.src}</button><ArrowRight size={17}/><button onClick={()=>onSelect(edge.dst)}><small>Получатель</small>{edge.dst}</button></div><p>Переводов за период выгрузки: {count(edge.n_tx)}</p><p className="muted">Сумма по направленной паре. Даты отдельных транзакций в этой таблице не переданы; временные признаки доступны в карточке участника.</p></section>
}
export default function EdgeEvidence({report,gid,onEdge,selected}:{report:Report;gid:string;onEdge:(edge:EdgeRecord)=>void;selected:EdgeRecord|null}) {
 const rows=report.edges.filter(e=>e.src===gid||e.dst===gid).sort((a,b)=>b.sum_kzt-a.sum_kzt)
 return <section className="analysis-panel"><div className="panel-heading"><div><div className="eyebrow">НАБЛЮДАЕМЫЕ ОПЕРАЦИИ</div><h2>Переводы участника</h2></div><span className="muted">{rows.length} направленных пар</span></div><div className="analysis-body"><p className="section-lead">Агрегаты из исходных рёбер. Выберите строку для точной суммы, количества переводов и направления.</p><div className="table-scroll"><table className="data-table transfers-table"><thead><tr><th>Направление / контрагент</th><th className="numeric">Сумма, KZT</th><th className="numeric">Переводов</th></tr></thead><tbody>{rows.map(e=><tr key={`${e.src}-${e.dst}`} data-selected={selected?.src===e.src&&selected?.dst===e.dst}><td><button onClick={()=>onEdge(e)} aria-label={`Открыть связь ${e.src} → ${e.dst}`}><span className="transfer-direction">{e.src===e.dst?'Самоперевод':e.dst===gid?'Входящий':'Исходящий'} <ArrowRight size={13}/></span><span className="mono">{e.dst===gid?e.src:e.dst}</span></button></td><td className="numeric">{money(e.sum_kzt)}</td><td className="numeric">{count(e.n_tx)}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty-evidence">В этой выгрузке у участника нет наблюдаемых переводов.</p>}</div></section>
}
