import { useMemo, useState } from 'react'
import { Minus, Plus, Maximize2, ChevronLeft, ChevronRight } from 'lucide-react'
import { Button } from './ui/button'
import { roles, roleColors, count, money, type Report, type NodeRecord, type EdgeRecord, type Role } from '../contract'
const palette=['#477c70','#627b9d','#9a755a','#90799a','#7c8955','#ae7474','#608994']
const compactMoney=(value:number)=>new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1}).format(value)+' ₸'
const gidCompare=(a:string,b:string)=>/^-?\d+$/.test(a)&&/^-?\d+$/.test(b)?(BigInt(a)<BigInt(b)?-1:BigInt(a)>BigInt(b)?1:0):a.localeCompare(b)
export default function Graph({report,selectedGid,onSelect,onEdge,selectedEdge}:{report:Report;selectedGid:string;onSelect:(gid:string)=>void;onEdge?:(edge:EdgeRecord)=>void;selectedEdge?:EdgeRecord|null}) {
 const [mobileDirection,setMobileDirection]=useState<'incoming'|'outgoing'>('incoming')
 const [mode,setMode]=useState<'roles'|'clusters'>('roles'),[zoom,setZoom]=useState(1),[incomingPage,setIncomingPage]=useState(0),[outgoingPage,setOutgoingPage]=useState(0),[focused,setFocused]=useState('')
 const data=useMemo(()=>{const order=(a:EdgeRecord,b:EdgeRecord)=>b.sum_kzt-a.sum_kzt||gidCompare(a.src===selectedGid?a.dst:a.src,b.src===selectedGid?b.dst:b.src);return {nodes:new Map(report.nodes.map(n=>[n.gid,n])),incoming:report.edges.filter(e=>e.dst===selectedGid&&e.src!==selectedGid).sort(order),outgoing:report.edges.filter(e=>e.src===selectedGid&&e.dst!==selectedGid).sort(order),self:report.edges.filter(e=>e.src===selectedGid&&e.dst===selectedGid)}},[report,selectedGid])
 const incoming=data.incoming.slice(incomingPage*6,(incomingPage+1)*6),outgoing=data.outgoing.slice(outgoingPage*6,(outgoingPage+1)*6),selected=data.nodes.get(selectedGid)!
 const maxAmount=Math.max(1,...incoming.map(e=>e.sum_kzt),...outgoing.map(e=>e.sum_kzt))
 const color=(n:NodeRecord)=>mode==='roles'?roleColors[n.role]:palette[Math.abs(n.cluster_id)%palette.length]
 const y=(index:number,total:number)=>240+(index-(total-1)/2)*70
 const drawNode=(n:NodeRecord,x:number,cy:number,chosen=false,side='center')=><g key={`${side}-${n.gid}`} data-node={n.gid} className="graph-node" role="button" tabIndex={0} aria-label={`Узел ${n.gid}: ${roles[n.role]}`} aria-pressed={chosen} onClick={()=>onSelect(n.gid)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(n.gid)}}} onFocus={()=>setFocused(n.gid)} onBlur={()=>setFocused('')} onMouseEnter={()=>setFocused(n.gid)} onMouseLeave={()=>setFocused('')}><title>{n.gid} — {roles[n.role]} · кластер {n.cluster_id}</title><rect x={x-(chosen?101:80)} y={cy-(chosen?45:25)} width={chosen?202:160} height={chosen?90:50} rx="7" fill={chosen?'#f0f6f2':'white'} stroke={chosen?'#216452':'#dbe3dd'} strokeWidth={chosen?2:1}/><rect x={x-(chosen?101:80)} y={cy-(chosen?45:25)+9} width="4" height={chosen?72:32} rx="2" fill={color(n)}/>{chosen&&<text x={x} y={cy-22} textAnchor="middle" className="svg-eyebrow">ВЫБРАННЫЙ УЧАСТНИК</text>}<text x={x} y={cy+(chosen?0:-3)} textAnchor="middle" className="svg-gid">{n.gid}</text><text x={x} y={cy+(chosen?22:15)} textAnchor="middle" className="svg-role">{mode==='roles'?roles[n.role]:`Кластер ${n.cluster_id}`}</text></g>
 const pager=(label:string,total:number,page:number,setPage:(v:number)=>void,prefix='')=><div className="lane-pager"><span>{label} <b>{count(total)}</b></span>{total>6&&<div><Button variant="ghost" size="icon" aria-label={`${prefix}Предыдущие ${label.toLowerCase()}`} disabled={page===0} onClick={()=>setPage(page-1)}><ChevronLeft/></Button><span>{page*6+1}–{Math.min((page+1)*6,total)}</span><Button variant="ghost" size="icon" aria-label={`${prefix}Следующие ${label.toLowerCase()}`} disabled={(page+1)*6>=total} onClick={()=>setPage(page+1)}><ChevronRight/></Button></div>}</div>
 return <section className="graph-section" aria-label="Граф связей"><div className="graph-toolbar"><div className="segmented" aria-label="Цвет графа"><Button variant={mode==='roles'?'secondary':'ghost'} aria-pressed={mode==='roles'} onClick={()=>setMode('roles')}>Цвет: роли</Button><Button variant={mode==='clusters'?'secondary':'ghost'} aria-pressed={mode==='clusters'} onClick={()=>setMode('clusters')}>Кластеры</Button></div><div className="controls"><Button variant="ghost" size="icon" aria-label="Отдалить" onClick={()=>setZoom(v=>Math.max(.75,v-.25))}><Minus/></Button><span>{Math.round(zoom*100)}%</span><Button variant="ghost" size="icon" aria-label="Приблизить" onClick={()=>setZoom(v=>Math.min(2,v+.25))}><Plus/></Button><Button variant="ghost" size="icon" aria-label="Показать целиком" onClick={()=>setZoom(1)}><Maximize2/></Button></div></div><div className="lane-headings">{pager('Отправители',data.incoming.length,incomingPage,setIncomingPage)}<span className="flow-direction">Движение денег →</span>{pager('Получатели',data.outgoing.length,outgoingPage,setOutgoingPage)}</div>
 <div className="mobile-flow" aria-label="Связи выбранного участника на узком экране"><div className="mobile-selected"><span>ВЫБРАННЫЙ УЧАСТНИК</span><strong>{selected.gid}</strong><p>{mode==='roles'?roles[selected.role]:`Кластер ${selected.cluster_id}`}</p><a className="inspector-jump" href="#participant-details">Основание и данные участника ↓</a></div><div className="mobile-flow-tabs"><Button variant={mobileDirection==='incoming'?'secondary':'ghost'} aria-pressed={mobileDirection==='incoming'} onClick={()=>setMobileDirection('incoming')}>Входящие · {data.incoming.length}</Button><Button variant={mobileDirection==='outgoing'?'secondary':'ghost'} aria-pressed={mobileDirection==='outgoing'} onClick={()=>setMobileDirection('outgoing')}>Исходящие · {data.outgoing.length}</Button></div><p className="mobile-direction">{mobileDirection==='incoming'?'Отправитель → выбранный участник':'Выбранный участник → получатель'}</p><div className="mobile-connections">{(mobileDirection==='incoming'?incoming:outgoing).map(edge=>{const n=data.nodes.get(mobileDirection==='incoming'?edge.src:edge.dst)!;return <button key={`${edge.src}-${edge.dst}`} aria-label={`Открыть ${n.gid} на мобильной схеме`} onClick={()=>onSelect(n.gid)}><span className="mobile-neighbor"><i style={{background:color(n)}}/><strong>{n.gid}</strong><span>{mode==='roles'?roles[n.role]:`Кластер ${n.cluster_id}`}</span></span><span className="mobile-amount">{money(edge.sum_kzt)}<small>Переводов: {count(edge.n_tx)}</small></span></button>})}{!(mobileDirection==='incoming'?data.incoming:data.outgoing).length&&<p className="mobile-empty">{mobileDirection==='incoming'?'Входящие переводы не наблюдаются':'Исходящие переводы не наблюдаются'}</p>}</div>{mobileDirection==='incoming'?pager('Отправители',data.incoming.length,incomingPage,setIncomingPage,'Мобильная схема: '):pager('Получатели',data.outgoing.length,outgoingPage,setOutgoingPage,'Мобильная схема: ')}{data.self.length>0&&<p className="mobile-direction">Самоперевод · {money(data.self.reduce((sum,e)=>sum+e.sum_kzt,0))}</p>}</div>
 <div className="graph-canvas"><svg viewBox="0 0 840 480" style={{width:`${zoom*100}%`,minWidth:580*zoom}} role="img" aria-label="Направленный граф выбранного узла"><defs><marker id="flow-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,0 L8,4 L0,8" fill="#80988b"/></marker></defs>{[190,650].map(x=><line key={x} x1={x} y1="15" x2={x} y2="465" stroke="#e8ede9" strokeDasharray="3 6"/>)}
 {[{edges:incoming,incoming:true},{edges:outgoing,incoming:false}].flatMap(group=>group.edges.map((edge,i)=>{const cy=y(i,group.edges.length),sx=group.incoming?175:521,ex=group.incoming?319:665,sy=group.incoming?cy:240,ey=group.incoming?240:cy;return <g key={`${group.incoming}-${edge.src}-${edge.dst}`} className="graph-edge" data-selected={selectedEdge?.src===edge.src&&selectedEdge?.dst===edge.dst} data-muted={!!selectedEdge&&(selectedEdge.src!==edge.src||selectedEdge.dst!==edge.dst)} role="button" tabIndex={0} onClick={()=>onEdge?.(edge)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onEdge?.(edge)}}} aria-label={`${edge.src} → ${edge.dst}: ${money(edge.sum_kzt)}, переводов: ${count(edge.n_tx)}`}><path className="edge-hit" d={`M ${sx} ${sy} C ${(sx+ex)/2} ${sy}, ${(sx+ex)/2} ${ey}, ${ex} ${ey}`} fill="none" stroke="transparent" strokeWidth={16}/><path d={`M ${sx} ${sy} C ${(sx+ex)/2} ${sy}, ${(sx+ex)/2} ${ey}, ${ex} ${ey}`} fill="none" stroke="#a7b9af" strokeWidth={1+edge.sum_kzt/maxAmount*2} markerEnd="url(#flow-arrow)"/><text x={group.incoming?205:635} y={cy-8} textAnchor={group.incoming?'start':'end'} className="svg-amount">{compactMoney(edge.sum_kzt)}</text><title>{money(edge.sum_kzt)} · переводов: {count(edge.n_tx)}</title></g>}))}
 {incoming.map((e,i)=>drawNode(data.nodes.get(e.src)!,95,y(i,incoming.length),false,'in'))}{outgoing.map((e,i)=>drawNode(data.nodes.get(e.dst)!,745,y(i,outgoing.length),false,'out'))}{drawNode(selected,420,240,true)}{!data.incoming.length&&<text x="95" y="240" textAnchor="middle" className="svg-empty">Нет входящих связей</text>}{!data.outgoing.length&&<text x="745" y="240" textAnchor="middle" className="svg-empty">Нет исходящих связей</text>}{data.self.length>0&&<g aria-label="Самоперевод"><path d="M 390 285 C 340 360 500 360 450 287" fill="none" stroke="#80988b" markerEnd="url(#flow-arrow)"/><text x="420" y="360" textAnchor="middle" className="svg-role">Самоперевод · {compactMoney(data.self.reduce((sum,e)=>sum+e.sum_kzt,0))}</text></g>}</svg></div>
 <div className="graph-focus" aria-live="polite">{focused?<><span>gid</span> <strong>{focused}</strong><span>· {roles[data.nodes.get(focused)!.role]}</span></>:<span>Участник открывает связи · стрелка открывает сумму и переводы</span>}</div><div className="graph-foot"><p>Окружение в один шаг · стрелка: плательщик → получатель</p><p className="desktop-count">Показано {incoming.length+outgoing.length+data.self.length} из {data.incoming.length+data.outgoing.length+data.self.length} связей. Суммы за весь период, KZT.</p><p className="mobile-count">Показано {mobileDirection==='incoming'?incoming.length:outgoing.length} из {mobileDirection==='incoming'?data.incoming.length:data.outgoing.length} {mobileDirection==='incoming'?'входящих':'исходящих'} связей. Суммы за весь период, KZT.</p><div className="legend">{mode==='roles'?Object.entries(roles).map(([role,label])=><span key={role}><i style={{background:roleColors[role as Role]}}/>{label}</span>):Array.from(new Set([selected,...incoming.map(e=>data.nodes.get(e.src)!),...outgoing.map(e=>data.nodes.get(e.dst)!)].map(n=>n.cluster_id))).sort((a,b)=>a-b).map(id=><span key={id}><i style={{background:palette[Math.abs(id)%palette.length]}}/>Кластер {id}</span>)}</div></div></section>
}
