import { useEffect, useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Network, Search, ShieldCheck, CircleAlert, ArrowDownLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import Graph from './components/Graph'
import { parseReport, roles, count, money, type Report, type NodeRecord } from './contract'
function Inspector({node,report,onSelect}:{node:NodeRecord;report:Report;onSelect:(gid:string)=>void}) {
 const cluster=report.clusters.find(c=>c.cluster_id===node.cluster_id),incoming=report.edges.filter(e=>e.dst===node.gid),outgoing=report.edges.filter(e=>e.src===node.gid)
 const metrics=[['Приоритет проверки',node.priority_score.toFixed(2)],['Оценка правила роли',node.role_score.toFixed(2)],['Входящие связи',count(node.in_degree)],['Исходящие связи',count(node.out_degree)],['Входящая сумма',money(node.in_sum)],['Исходящая сумма',money(node.out_sum)],['Транзит средств',node.pass_through===null?'Нет данных':node.pass_through.toFixed(2)],['Seed-предки',count(node.seed_ancestors)]]
 return <Card className="inspector"><CardContent><div className="eyebrow">КАРТОЧКА УЧАСТНИКА</div><h2>Узел {node.gid}</h2><div className="badges"><Badge variant="secondary">{roles[node.role]}</Badge><Badge variant="outline">Глубина {node.depth}</Badge>{node.is_seed&&<Badge variant="outline">Seed</Badge>}</div><p className="evidence">{node.evidence}</p><p className="muted small">Роль — гипотеза по наблюдаемым переводам.</p><dl className="metrics">{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 {(node.is_seed||node.boundary_censored||node.warnings.length>0)&&<div className="node-warnings">{node.is_seed&&<p>Входящие переводы вне выборки не видны</p>}{node.boundary_censored&&<p>Граница выгрузки: отсутствие исходящих не доказывает конечного получателя</p>}{node.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}
 {!incoming.length&&!outgoing.length&&<p className="isolate">В этой выгрузке у узла нет связей. Это не доказывает отсутствие переводов за её пределами.</p>}
 {[{label:'Входящие',edges:incoming,in:true},{label:'Исходящие',edges:outgoing,in:false}].map(group=><section className="neighbors" key={group.label}><h3>{group.in?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>} {group.label} <span>{group.edges.length}</span></h3>{group.edges.length===0?<p className="muted small">В выборке не наблюдаются</p>:<ul>{group.edges.map((e,i)=>{const id=group.in?e.src:e.dst;return <li key={`${id}-${i}`}><button aria-label={`Открыть соседний узел ${id}`} onClick={()=>onSelect(id)}>{id}<ArrowUpRight size={14}/></button><span>{money(e.sum_kzt)} · {count(e.n_tx)} переводов</span></li>})}</ul>}</section>)}
 {cluster&&<section className="cluster-details"><h3>Кластер {cluster.cluster_id}</h3><p className="small muted">{count(cluster.n_nodes)} узлов · {count(cluster.n_seed)} seed · {money(cluster.sum_kzt_internal)} внутри</p><p>{cluster.hypothesis}</p><div className="cluster-gids">{cluster.top_gids.map(id=><button key={id} onClick={()=>onSelect(id)} aria-label={`Открыть узел ${id} из кластера`}>{id}</button>)}</div></section>}
 </CardContent></Card>
}
export default function App() {
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[retry,setRetry]=useState(0),[searchMessage,setSearchMessage]=useState('')
 useEffect(()=>{let ignore=false;const controller=new AbortController();setError('');setReport(null);fetch('/data/report.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(parseReport).then(r=>{if(!ignore){setReport(r);setSelected(r.top_nodes[0]?.gid??'')}}).catch(e=>{if(!ignore)setError(String(e.message))});return()=>{ignore=true;controller.abort()}},[retry])
 const node=report?.nodes.find(n=>n.gid===selected)
 const select=(id:string)=>{setSelected(id);setSearchMessage('')}
 const search=()=>{const id=query.trim();if(!id){setSearchMessage('Введите gid, чтобы открыть узел и его связи.');return}if(report?.nodes.some(n=>n.gid===id))select(id);else setSearchMessage('Узел не найден. Проверьте gid и повторите поиск.')}
 return <div className="app-shell"><header className="header"><div className="brand"><span className="brand-icon"><Network size={24}/></span><div><h1>Граф денег</h1><p>Приоритеты проверки и связи участников</p></div></div><div className="header-meta"><span className="local-label"><i/> Локальный анализ</span>{report?.meta.period_start&&<span>{report.meta.period_start.slice(0,10)} — {report.meta.period_end.slice(0,10)}</span>}</div></header>
 <main><div className="disclaimer"><ShieldCheck size={18}/><span>Роли и приоритеты — гипотезы для проверки, не оценка виновности</span></div>
 {error?<Alert className="load-state" role="alert"><CircleAlert/><AlertDescription><h2>Не удалось загрузить результаты анализа.</h2><p>Проверьте, что локальный расчёт завершён, и повторите загрузку.</p><p>{error}</p><Button variant="outline" onClick={()=>setRetry(retry+1)}>Повторить загрузку</Button></AlertDescription></Alert>:!report?<div className="load-state" role="status"><p>Загружаем граф и результаты анализа…</p><div className="skeleton"/></div>:report.nodes.length===0?<Card className="load-state"><CardContent><h2>В выгрузке пока нет узлов</h2><p>Выполните локальный расчёт и обновите страницу.</p></CardContent></Card>:<>
 <section className="stats" aria-label="Сводка данных">{[['Участники сети',count(report.nodes.length)],['Направленные связи',count(report.edges.length)],['Транзакции',count(report.meta.n_transactions)],['Объём переводов',money(report.meta.total_kzt)]].map(([label,value])=><Card key={label}><CardContent><p>{label}</p><strong>{value}</strong></CardContent></Card>)}</section>
 <div className="workspace-title"><div><div className="eyebrow">ИССЛЕДОВАНИЕ СЕТИ</div><h2>От приоритета — к связям</h2></div><span className="small muted">{count(report.clusters.length)} кластеров · {count(report.meta.n_seed)} seed</span></div>
 <form className="search-form" onSubmit={e=>{e.preventDefault();search()}}><div className="search-field"><label htmlFor="gid">Поиск по gid</label><div className="input-wrap"><Search size={18}/><Input id="gid" placeholder="Введите gid" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)} aria-describedby="search-feedback"/></div></div><Button type="submit">Найти узел <ArrowUpRight size={16}/></Button><p id="search-feedback" role="status">{searchMessage||'Найдите любого участника, включая узлы без связей.'}</p></form>
 {report.meta.warnings.length>0&&<details className="dataset-warnings"><summary>Ограничения выгрузки · {report.meta.warnings.length}</summary>{report.meta.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
 <div className="workspace"><Card className="graph-card"><div className="panel-heading"><div><h2>Связи участника</h2><p>Входящие и исходящие переводы выбранного узла</p></div><Badge variant="outline">Направленный граф</Badge></div>{node?<Graph key={node.gid} report={report} selectedGid={node.gid} onSelect={select}/>:<div className="no-selection">Выберите узел на графе, в списке или найдите его по gid.</div>}</Card>{node?<Inspector node={node} report={report} onSelect={select}/>:<Card><CardContent className="no-selection">Выберите узел на графе, в списке или найдите его по gid.</CardContent></Card>}</div>
 <Card className="ranking"><div className="panel-heading"><div><div className="eyebrow">ПРИОРИТЕТЫ ПРОВЕРКИ</div><h2>С чего начать исследование</h2><p>Сначала — участники с наиболее выраженными структурными признаками.</p></div><Badge variant="secondary">{report.top_nodes.length} участников</Badge></div>{report.top_nodes.length===0?<p className="empty-ranking">Список приоритетов пуст. Найдите узел по gid, чтобы изучить его связи.</p>:<div role="region" aria-label="Рейтинг участников" className="ranking-scroll" tabIndex={0}><Table><TableHeader><TableRow><TableHead>Место</TableHead><TableHead>Участник · gid</TableHead><TableHead>Гипотеза роли</TableHead><TableHead>Приоритет</TableHead><TableHead>Основание для проверки</TableHead></TableRow></TableHeader><TableBody>{report.top_nodes.map(t=><TableRow key={t.gid} data-selected={selected===t.gid}><TableCell className="rank-number">{String(t.rank).padStart(2,'0')}</TableCell><TableCell><button className="gid-link" aria-label={`Открыть узел ${t.gid} из рейтинга`} onClick={()=>select(t.gid)}>{t.gid}<ArrowUpRight size={14}/></button></TableCell><TableCell>{roles[t.role]}</TableCell><TableCell><span className="score">{t.priority_score.toFixed(2)}</span></TableCell><TableCell className="why">{t.why}</TableCell></TableRow>)}</TableBody></Table></div>}</Card>
 <footer><p>Результаты локального расчёта <span>· CSV без изменения исходных данных</span></p><div className="downloads">{[['nodes_roles','роли'],['clusters','кластеры'],['top_nodes','приоритеты']].map(([file,label])=><Button key={file} variant="outline" asChild><a href={`/data/${file}.csv`} download><ArrowDownToLine size={16}/> Скачать {label} CSV</a></Button>)}</div></footer>
 <p className="sr-only" aria-live="polite">{node?`Выбран узел ${node.gid}`:''}</p>
 </>}
 </main></div>
}
