import { useEffect, useRef, useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Network, Search, ShieldCheck, CircleAlert, ArrowDownLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import Graph from './components/Graph'
import { parseReport, roles, count, money, type Report, type NodeRecord, type TemporalEvidence } from './contract'
const observations=(value:number|undefined)=>value===undefined?'Нет данных':`${count(value)} наблюдений`
const gidOrder=(left:string,right:string)=>/^-?\d+$/.test(left)&&/^-?\d+$/.test(right)?(BigInt(left)<BigInt(right)?-1:BigInt(left)>BigInt(right)?1:0):left.localeCompare(right,'ru')
const nodeNoun=(value:number)=>value%10===1&&value%100!==11?'узел':value%10>=2&&value%10<=4&&(value%100<12||value%100>14)?'узла':'узлов'
function FilterSelect({id,label,value,onChange,options}:{id:string;label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}) {
 return <div className="filter-field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{options.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>
}
function TemporalSection({temporal,boundary}:{temporal:TemporalEvidence;boundary:boolean}) {
 const peak=temporal.peak_day,profile=temporal.incoming_profile,sync=temporal.synchronous_incoming
 return <section className="temporal-section"><h3>Временные признаки</h3><p className="small muted">Наблюдаемые переводы и совпадения календарных дат</p>
 <dl className="temporal-metrics"><div><dt>Входящие транзакции</dt><dd>{observations(temporal.incoming_tx_count)}</dd></div><div><dt>Исходящие транзакции</dt><dd>{observations(temporal.outgoing_tx_count)}</dd></div><div><dt>Через 1 день после поступления</dt><dd>{observations(temporal.outgoing_after_1d_count)}</dd></div><div><dt>Через 1–2 дня после поступления</dt><dd>{observations(temporal.outgoing_after_1_or_2d_count)}</dd></div></dl>
 <p className="small muted">Каждый подходящий исходящий перевод учтён один раз. Показатель за 1–2 дня накопительный: он включает переводы за 1 день; эти значения не складываются.</p>
 {!!temporal.after_1_or_2d_examples?.length&&<div className="temporal-subsection"><h3>Примеры дат</h3><ul>{temporal.after_1_or_2d_examples.map((pair,i)=><li key={`${pair.incoming_date}-${pair.outgoing_date}-${i}`}>{pair.incoming_date} → {pair.outgoing_date}</li>)}</ul></div>}
 {profile&&<div className="temporal-subsection"><h3>Профиль входящих</h3><p>{count(profile.distinct_payers)} плательщика · {count(profile.active_days)} активных дней</p><p>{money(profile.total_kzt)} всего · {money(profile.median_kzt)} медиана перевода</p>{boundary&&<p className="small muted">Граница глубины 4: наблюдаемые поступления не доказывают, что узел — конечный получатель.</p>}</div>}
 {sync&&<div className="temporal-subsection"><h3>Синхронные поступления</h3><p>{sync.date}: {count(sync.distinct_payers)} плательщика, {count(sync.tx_count)} транзакций, {money(sync.sum_kzt)}</p><p className="small muted">Совпадение календарного дня не задаёт порядок переводов внутри дня.</p></div>}
 {peak&&<div className="temporal-subsection"><h3>Пик дневной активности</h3><p>{peak.date}: {count(peak.count)} транзакций · {new Intl.NumberFormat('ru-RU',{style:'percent',maximumFractionDigits:1}).format(peak.share)} от всех наблюдаемых · базовый уровень {new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(peak.baseline_daily_count)} в день</p><p className="small muted">Пик показан при трёх и более транзакциях за день и уровне не ниже двойного среднего за весь период.</p></div>}
 <p className="temporal-caution">Совпадение дат не доказывает, что переводились те же деньги.</p></section>
}
function Inspector({node,report,onSelect}:{node:NodeRecord;report:Report;onSelect:(gid:string)=>void}) {
 const cluster=report.clusters.find(c=>c.cluster_id===node.cluster_id),incoming=report.edges.filter(e=>e.dst===node.gid),outgoing=report.edges.filter(e=>e.src===node.gid)
 const metrics=[['Приоритет проверки',node.priority_score.toFixed(2)],['Оценка правила роли',node.role_score.toFixed(2)],['Входящие связи',count(node.in_degree)],['Исходящие связи',count(node.out_degree)],['Входящая сумма',money(node.in_sum)],['Исходящая сумма',money(node.out_sum)],['Транзит средств',node.pass_through===null?'Нет данных':node.pass_through.toFixed(2)],['Seed-предки',count(node.seed_ancestors)]]
 return <Card className="inspector"><CardContent><div className="eyebrow">КАРТОЧКА УЧАСТНИКА</div><h2>Узел {node.gid}</h2><div className="badges"><Badge variant="secondary">{roles[node.role]}</Badge><Badge variant="outline">Глубина {node.depth}</Badge>{node.is_seed&&<Badge variant="outline">Seed</Badge>}</div><p className="evidence">{node.evidence}</p><p className="muted small">Роль — гипотеза по наблюдаемым переводам.</p><dl className="metrics">{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 {(node.is_seed||node.boundary_censored||node.warnings.length>0)&&<div className="node-warnings">{node.is_seed&&<p>Входящие переводы вне выборки не видны</p>}{node.boundary_censored&&<p>Граница выгрузки: отсутствие исходящих не доказывает конечного получателя</p>}{node.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}
 {node.temporal&&<TemporalSection temporal={node.temporal} boundary={node.boundary_censored}/>}
 {node.next_data_requests&&<section className="request-section"><h3>Какие данные запросить дальше</h3>{node.next_data_requests.length?<ul>{node.next_data_requests.map((request,i)=><li key={i}>{request}</li>)}</ul>:<p className="small muted">Дополнительный запрос данных не определён для этого узла.</p>}</section>}
 {!incoming.length&&!outgoing.length&&<p className="isolate">В этой выгрузке у узла нет связей. Это не доказывает отсутствие переводов за её пределами.</p>}
 {[{label:'Входящие',edges:incoming,in:true},{label:'Исходящие',edges:outgoing,in:false}].map(group=><section className="neighbors" key={group.label}><h3>{group.in?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>} {group.label} <span>{group.edges.length}</span></h3>{group.edges.length===0?<p className="muted small">В выборке не наблюдаются</p>:<ul>{group.edges.map((e,i)=>{const id=group.in?e.src:e.dst;return <li key={`${id}-${i}`}><button aria-label={`Открыть соседний узел ${id}`} onClick={()=>onSelect(id)}>{id}<ArrowUpRight size={14}/></button><span>{money(e.sum_kzt)} · {count(e.n_tx)} переводов</span></li>})}</ul>}</section>)}
 {cluster&&<section className="cluster-details"><h3>Кластер {cluster.cluster_id}</h3><p className="small muted">{count(cluster.n_nodes)} узлов · {count(cluster.n_seed)} seed · {money(cluster.sum_kzt_internal)} внутри</p><p>{cluster.hypothesis}</p><div className="cluster-gids">{cluster.top_gids.map(id=><button key={id} onClick={()=>onSelect(id)} aria-label={`Открыть узел ${id} из кластера`}>{id}</button>)}</div></section>}
 </CardContent></Card>
}
export default function App() {
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[retry,setRetry]=useState(0),[searchMessage,setSearchMessage]=useState('')
 const [roleFilter,setRoleFilter]=useState('all'),[clusterFilter,setClusterFilter]=useState('all'),[seedFilter,setSeedFilter]=useState('all'),[boundaryFilter,setBoundaryFilter]=useState('all'),[visibleCount,setVisibleCount]=useState(20)
 const resultsHeading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>{let ignore=false;const controller=new AbortController();setError('');setReport(null);fetch('/data/report.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(parseReport).then(r=>{if(!ignore){setReport(r);setSelected(r.top_nodes[0]?.gid??'')}}).catch(e=>{if(!ignore)setError(String(e.message))});return()=>{ignore=true;controller.abort()}},[retry])
 const node=report?.nodes.find(n=>n.gid===selected)
 const select=(id:string)=>{setSelected(id);setSearchMessage('')}
 const search=()=>{const id=query.trim();if(!id){setSearchMessage('Введите gid, чтобы открыть узел и его связи.');return}if(report?.nodes.some(n=>n.gid===id))select(id);else setSearchMessage('Узел не найден. Проверьте gid и повторите поиск.')}
 const updateFilter=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setVisibleCount(20)}
 const resetFilters=()=>{setRoleFilter('all');setClusterFilter('all');setSeedFilter('all');setBoundaryFilter('all');setVisibleCount(20)}
 const hasFilters=[roleFilter,clusterFilter,seedFilter,boundaryFilter].some(value=>value!=='all')
 const filtered=report?.nodes.filter(item=>(roleFilter==='all'||item.role===roleFilter)&&(clusterFilter==='all'||String(item.cluster_id)===clusterFilter)&&(seedFilter==='all'||item.is_seed===(seedFilter==='yes'))&&(boundaryFilter==='all'||item.boundary_censored===(boundaryFilter==='yes'))).sort((a,b)=>b.priority_score-a.priority_score||gidOrder(a.gid,b.gid))??[]
 const visible=filtered.slice(0,visibleCount)
 const clusterOptions=report?.clusters.map(cluster=>cluster.cluster_id).sort((a,b)=>a-b)??[]
 const investigateCluster=(id:number)=>{setClusterFilter(String(id));setVisibleCount(20);resultsHeading.current?.focus()}
 return <div className="app-shell"><header className="header"><div className="brand"><span className="brand-icon"><Network size={24}/></span><div><h1>Граф денег</h1><p>Приоритеты проверки и связи участников</p></div></div><div className="header-meta"><span className="local-label"><i/> Локальный анализ</span>{report?.meta.period_start&&<span>{report.meta.period_start.slice(0,10)} — {report.meta.period_end.slice(0,10)}</span>}</div></header>
 <main><div className="disclaimer"><ShieldCheck size={18}/><span>Роли и приоритеты — гипотезы для проверки, не оценка виновности</span></div>
 {error?<Alert className="load-state" role="alert"><CircleAlert/><AlertDescription><h2>Не удалось загрузить результаты анализа.</h2><p>Проверьте, что локальный расчёт завершён, и повторите загрузку.</p><p>{error}</p><Button variant="outline" onClick={()=>setRetry(retry+1)}>Повторить загрузку</Button></AlertDescription></Alert>:!report?<div className="load-state" role="status"><p>Загружаем граф и результаты анализа…</p><div className="skeleton"/></div>:report.nodes.length===0?<Card className="load-state"><CardContent><h2>В выгрузке пока нет узлов</h2><p>Выполните локальный расчёт и обновите страницу.</p></CardContent></Card>:<>
 <section className="stats" aria-label="Сводка данных">{[['Участники сети',count(report.nodes.length)],['Направленные связи',count(report.edges.length)],['Транзакции',count(report.meta.n_transactions)],['Объём переводов',money(report.meta.total_kzt)]].map(([label,value])=><Card key={label}><CardContent><p>{label}</p><strong>{value}</strong></CardContent></Card>)}</section>
 <div className="workspace-title"><div><div className="eyebrow">ИССЛЕДОВАНИЕ СЕТИ</div><h2>От приоритета — к связям</h2></div><span className="small muted">{count(report.clusters.length)} кластеров · {count(report.meta.n_seed)} seed</span></div>
 <form className="search-form" onSubmit={e=>{e.preventDefault();search()}}><div className="search-field"><label htmlFor="gid">Поиск по gid</label><div className="input-wrap"><Search size={18}/><Input id="gid" placeholder="Введите gid" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)} aria-describedby="search-feedback"/></div></div><Button type="submit">Найти узел <ArrowUpRight size={16}/></Button><p id="search-feedback" role="status">{searchMessage||'Найдите любого участника, включая узлы без связей.'}</p></form>
 <section className="exploration" aria-labelledby="exploration-title"><div className="exploration-heading"><div><div className="eyebrow">ВЫБОРКА И СООБЩЕСТВА</div><h2 id="exploration-title">Исследование выборки</h2><p className="small muted">Фильтры меняют только список ниже. Поиск по gid доступен для всей сети.</p></div>{hasFilters&&<Button variant="outline" onClick={resetFilters}>Сбросить фильтры</Button>}</div>
 <div className="filter-grid"><FilterSelect id="role-filter" label="Роль" value={roleFilter} onChange={updateFilter(setRoleFilter)} options={[{value:'all',label:'Все'},...Object.entries(roles).map(([value,label])=>({value,label}))]}/><FilterSelect id="cluster-filter" label="Кластер" value={clusterFilter} onChange={updateFilter(setClusterFilter)} options={[{value:'all',label:'Все'},...clusterOptions.map(id=>({value:String(id),label:`Кластер ${id}`}))]}/><FilterSelect id="seed-filter" label="Seed" value={seedFilter} onChange={updateFilter(setSeedFilter)} options={[{value:'all',label:'Все'},{value:'yes',label:'Только seed'},{value:'no',label:'Без seed'}]}/><FilterSelect id="boundary-filter" label="Граница выгрузки" value={boundaryFilter} onChange={updateFilter(setBoundaryFilter)} options={[{value:'all',label:'Все'},{value:'yes',label:'Граничные'},{value:'no',label:'Неграничные'}]}/></div>
 <div className="exploration-panels"><Card className="results-card"><CardContent><div className="results-heading"><div><h3 ref={resultsHeading} tabIndex={-1}>Результаты исследования</h3><p className="small muted" aria-live="polite"><span>Показано {visible.length} из {report.nodes.length} узлов</span><span> · в выборке: {filtered.length} {nodeNoun(filtered.length)}</span></p></div></div>{filtered.length===0?<div className="filtered-empty"><h3>По этим фильтрам узлы не найдены</h3><p className="small muted">Измените условия или сбросьте фильтры, чтобы увидеть всю выборку.</p></div>:<><div className="results-list" role="region" aria-label="Результаты исследования: узлы" tabIndex={0}>{visible.map(item=><button key={item.gid} className="result-row" data-selected={selected===item.gid} aria-label={`Открыть узел ${item.gid}`} onClick={()=>select(item.gid)}><span className="result-gid">{item.gid}<ArrowUpRight size={14}/></span><span className="small muted">{roles[item.role]} · кластер {item.cluster_id} · приоритет {item.priority_score.toFixed(2)}</span><span className="result-badges">{item.is_seed&&<Badge variant="outline">Seed</Badge>}{item.boundary_censored&&<Badge variant="outline">Граница</Badge>}</span></button>)}</div>{visible.length<filtered.length&&<Button variant="outline" className="more-results" onClick={()=>setVisibleCount(value=>value+20)}>Показать ещё</Button>}</>}</CardContent></Card>
 <Card className="clusters-card"><CardContent><h3>Обзор кластеров</h3><p className="small muted">Наблюдаемые сообщества в выгрузке</p>{report.clusters.length===0?<p className="small muted cluster-empty">Кластеры не представлены в этой выгрузке.</p>:<div className="cluster-list" role="region" aria-label="Обзор кластеров" tabIndex={0}>{[...report.clusters].sort((a,b)=>a.cluster_id-b.cluster_id).map(cluster=><div key={cluster.cluster_id} className="cluster-row" data-active={clusterFilter===String(cluster.cluster_id)}><Button variant="ghost" onClick={()=>investigateCluster(cluster.cluster_id)} aria-label={`Исследовать кластер ${cluster.cluster_id}`}>Кластер {cluster.cluster_id}<ArrowUpRight size={14}/></Button><p className="small muted">{count(cluster.n_nodes)} узлов · {count(cluster.n_seed)} seed · {money(cluster.sum_kzt_internal)} внутри</p><p className="small">{cluster.hypothesis}</p></div>)}</div>}</CardContent></Card></div></section>
 {report.meta.warnings.length>0&&<details className="dataset-warnings"><summary>Ограничения выгрузки · {report.meta.warnings.length}</summary>{report.meta.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
 {report.has_invalid_optional&&<p className="optional-warning" role="status">Часть дополнительных данных недоступна. Основные сведения об узле сохранены.</p>}
 <div className="workspace"><Card className="graph-card"><div className="panel-heading"><div><h2>Связи участника</h2><p>Входящие и исходящие переводы выбранного узла</p></div><Badge variant="outline">Направленный граф</Badge></div>{node?<Graph key={node.gid} report={report} selectedGid={node.gid} onSelect={select}/>:<div className="no-selection">Выберите узел на графе, в списке или найдите его по gid.</div>}</Card>{node?<Inspector node={node} report={report} onSelect={select}/>:<Card><CardContent className="no-selection">Выберите узел на графе, в списке или найдите его по gid.</CardContent></Card>}</div>
 <Card className="ranking"><div className="panel-heading"><div><div className="eyebrow">ПРИОРИТЕТЫ ПРОВЕРКИ</div><h2>С чего начать исследование</h2><p>Сначала — участники с наиболее выраженными структурными признаками.</p></div><Badge variant="secondary">{report.top_nodes.length} участников</Badge></div>{report.top_nodes.length===0?<p className="empty-ranking">Список приоритетов пуст. Найдите узел по gid, чтобы изучить его связи.</p>:<div role="region" aria-label="Рейтинг участников" className="ranking-scroll" tabIndex={0}><Table><TableHeader><TableRow><TableHead>Место</TableHead><TableHead>Участник · gid</TableHead><TableHead>Гипотеза роли</TableHead><TableHead>Приоритет</TableHead><TableHead>Основание для проверки</TableHead></TableRow></TableHeader><TableBody>{report.top_nodes.map(t=><TableRow key={t.gid} data-selected={selected===t.gid}><TableCell className="rank-number">{String(t.rank).padStart(2,'0')}</TableCell><TableCell><button className="gid-link" aria-label={`Открыть узел ${t.gid} из рейтинга`} onClick={()=>select(t.gid)}>{t.gid}<ArrowUpRight size={14}/></button></TableCell><TableCell>{roles[t.role]}</TableCell><TableCell><span className="score">{t.priority_score.toFixed(2)}</span></TableCell><TableCell className="why">{t.why}</TableCell></TableRow>)}</TableBody></Table></div>}</Card>
 <Card className="analysis-flow"><CardContent><div><div className="eyebrow">ПУТЬ ДАННЫХ</div><h2>Как устроен анализ</h2></div><ol><li><strong>Данные</strong><span>nodes / edges / transactions</span></li><li><strong>Метрики</strong><span>связи, суммы, даты</span></li><li><strong>Гипотезы</strong><span>роли, кластеры, приоритет</span></li><li><strong>Результат</strong><span>карточки, граф и 3 CSV</span></li></ol></CardContent></Card>
 <footer><p>Результаты локального расчёта <span>· CSV без изменения исходных данных</span></p><div className="downloads">{[['nodes_roles','роли'],['clusters','кластеры'],['top_nodes','приоритеты']].map(([file,label])=><Button key={file} variant="outline" asChild><a href={`/data/${file}.csv`} download><ArrowDownToLine size={16}/> Скачать {label} CSV</a></Button>)}</div></footer>
 <p className="sr-only" aria-live="polite">{node?`Выбран узел ${node.gid}`:''}</p>
 </>}
 </main></div>
}
