import '@testing-library/jest-dom/vitest'
import { cleanup, render, screen, fireEvent } from '@testing-library/react'
import { afterEach, beforeAll, expect, test, vi } from 'vitest'
import App from './App'
import { parseReport } from './contract'
// Entirely synthetic fixture: never imported into production code.
const gid = '999999999999999991'
const node = {gid,depth:4,is_seed:false,role:'peripheral',role_score:0.2,cluster_id:0,priority_score:0.3,evidence:'Синтетический узел для проверки точности gid',in_degree:0,out_degree:0,in_sum:0,out_sum:0,pass_through:null,boundary_censored:true,seed_ancestors:0,betweenness:0,warnings:[]}
const fixture = {schema_version:'1.0',meta:{n_nodes:1,n_edges:0,n_transactions:0,n_seed:0,total_kzt:0,period_start:'2025-01-01',period_end:'2025-02-01',elapsed_seconds:0,warnings:[]},nodes:[node],edges:[],clusters:[{cluster_id:0,n_nodes:1,n_seed:0,sum_kzt_internal:0,top_gids:[gid],hypothesis:'Синтетическое сообщество'}],top_nodes:[]}
beforeAll(()=>{HTMLElement.prototype.scrollIntoView=vi.fn()})
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
test('exact string gid beyond safe integer finds fetched evidence', async () => {
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>fixture}))
 render(<App />)
 fireEvent.change(await screen.findByLabelText('Поиск по gid'),{target:{value:gid}})
 fireEvent.click(screen.getByRole('button',{name:'Найти узел'}))
 expect(await screen.findByText(node.evidence)).toBeVisible()
})
test('isolated boundary node keeps selection after unknown search and explains limits',async()=>{
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,top_nodes:[{rank:1,gid,role:'peripheral',priority_score:0.3,why:'Проверить изолят'}]})}))
 render(<App />)
 expect(await screen.findByText('Граница выгрузки: отсутствие исходящих не доказывает конечного получателя')).toBeVisible()
 expect(screen.getByText('В этой выгрузке у узла нет связей. Это не доказывает отсутствие переводов за её пределами.')).toBeVisible()
 fireEvent.change(screen.getByLabelText('Поиск по gid'),{target:{value:'missing'}})
 fireEvent.click(screen.getByRole('button',{name:'Найти узел'}))
 expect(screen.getByText('Узел не найден. Проверьте gid и повторите поиск.')).toBeVisible()
 expect(screen.getByRole('heading',{name:`Узел ${gid}`})).toBeVisible()
})
test('ranking and directed neighbor buttons use same selection',async()=>{
 const other={...node,gid:'999999999999999992',evidence:'Второй синтетический узел',is_seed:true}
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[node,other],edges:[{src:gid,dst:other.gid,sum_kzt:120,n_tx:2}],top_nodes:[{rank:1,gid,role:'peripheral',priority_score:0.3,why:'Проверить'}]})}))
 render(<App />)
 fireEvent.click(await screen.findByText('Исходящие связи · 1',{selector:'summary'}))
 fireEvent.click(await screen.findByRole('button',{name:`Открыть соседний узел ${other.gid}`}))
 expect(screen.getByRole('heading',{name:`Узел ${other.gid}`})).toBeVisible()
 expect(screen.getByText('Входящие переводы вне выборки не видны')).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:`Открыть узел ${gid} из рейтинга`}))
 expect(screen.getByRole('heading',{name:`Узел ${gid}`})).toBeVisible()
})
test('loading, fetch failure and retry have actionable distinct states',async()=>{
 vi.stubGlobal('fetch',vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ok:true,json:async()=>fixture}).mockResolvedValue({ok:true,json:async()=>({status:'disabled',enabled:false})}))
 render(<App />)
 expect(screen.getByText('Загружаем граф и результаты анализа…')).toBeVisible()
 expect(await screen.findByRole('alert')).toHaveTextContent('Не удалось загрузить результаты анализа.')
 fireEvent.click(screen.getByRole('button',{name:'Повторить загрузку'}))
 expect(await screen.findByLabelText('Поиск по gid')).toBeVisible()
})
test('empty report and unsupported schema are explained',async()=>{
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[],clusters:[]})}))
 const view=render(<App />)
 expect(await screen.findByText('В выгрузке пока нет узлов')).toBeVisible()
 view.unmount()
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,schema_version:'2.0'})}))
 render(<App />)
 expect(await screen.findByRole('alert')).toHaveTextContent('Неподдерживаемая версия схемы отчёта.')
})
test('validator rejects unsafe identifiers, dangling references and nonfinite numbers',()=>{
 expect(()=>parseReport({...fixture,nodes:[{...node,gid:999}]})).toThrow()
 expect(()=>parseReport({...fixture,edges:[{src:gid,dst:'missing',sum_kzt:1,n_tx:1}]})).toThrow()
 expect(()=>parseReport({...fixture,nodes:[{...node,in_sum:Infinity}]})).toThrow()
 expect(()=>parseReport({...fixture,nodes:[node,node]})).toThrow()
})
test('CSV links and graph controls have accessible names',async()=>{
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,top_nodes:[{rank:1,gid,role:'peripheral',priority_score:0.3,why:'Проверить'}]})}))
 render(<App />)
 fireEvent.click(await screen.findByText('Выгрузить CSV',{selector:'summary'}))
 expect(await screen.findByRole('link',{name:'Скачать роли CSV'})).toHaveAttribute('href','/data/nodes_roles.csv')
 expect(screen.getByRole('link',{name:'Скачать кластеры CSV'})).toHaveAttribute('href','/data/clusters.csv')
 expect(screen.getByRole('link',{name:'Скачать приоритеты CSV'})).toHaveAttribute('href','/data/top_nodes.csv')
 fireEvent.click(screen.getByRole('button',{name:'Рабочая область'}))
 fireEvent.click(screen.getByRole('button',{name:'Кластеры'}))
 expect(screen.getByRole('button',{name:'Кластеры'})).toHaveAttribute('aria-pressed','true')
 fireEvent.click(screen.getByRole('button',{name:'Приблизить'}))
 expect(screen.getByRole('img',{name:'Направленный граф выбранного узла'})).toBeVisible()
})
test('workspace navigation exposes actual aggregate transfers and adjacent evidence without invented dates',async()=>{
 const other={...node,gid:'222',evidence:'Другой участник'}
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[node,other],edges:[{src:gid,dst:'222',sum_kzt:12000,n_tx:3}]})}))
 render(<App />)
 await screen.findByLabelText('Поиск по gid')
 fireEvent.click(screen.getByRole('button',{name:'Переводы'}))
 fireEvent.click(screen.getByRole('button',{name:`Открыть связь ${gid} → 222`}))
 expect(screen.getByLabelText('Данные выбранной связи')).toHaveTextContent('Переводов за период выгрузки: 3')
 expect(screen.getByLabelText('Данные выбранной связи')).toHaveTextContent('Даты отдельных транзакций в этой таблице не переданы')
 fireEvent.click(screen.getByRole('button',{name:'Закрыть данные связи'}))
 expect(screen.queryByLabelText('Данные выбранной связи')).not.toBeInTheDocument()
 fireEvent.click(screen.getByRole('button',{name:'Маршруты и возвраты'}))
 expect(screen.getByText('В этом отчёте маршруты не рассчитаны.')).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:'Устойчивость сети'}))
 expect(screen.getByText('В этом отчёте устойчивость сети не рассчитана.')).toBeVisible()
})
test('selected node shows dated temporal evidence, incoming profile and ordered requests',async()=>{
 const temporal={incoming_tx_count:5,outgoing_tx_count:4,outgoing_after_1d_count:2,outgoing_after_1_or_2d_count:3,after_1_or_2d_examples:[{incoming_date:'2025-01-02',outgoing_date:'2025-01-03'},{incoming_date:'2025-01-02',outgoing_date:'2025-01-04'}],incoming_profile:{active_days:2,total_kzt:900,distinct_payers:3,median_kzt:150},synchronous_incoming:{date:'2025-01-02',distinct_payers:3,tx_count:4,sum_kzt:800},peak_day:{date:'2025-01-03',count:3,share:0.3,baseline_daily_count:0.5}}
 const requests=['Запросить продолжение после глубины 4 для '+gid,'Запросить время и идентификаторы переводов 2025-01-02 для '+gid]
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[{...node,temporal,next_data_requests:requests}],top_nodes:[{rank:1,gid,role:'peripheral',priority_score:0.3,why:'Проверить'}]})}))
 render(<App />)
 fireEvent.click(await screen.findByText('Временные признаки',{selector:'summary'}))
 fireEvent.click(screen.getByText('Какие данные запросить дальше',{selector:'summary'}))
 expect(await screen.findByRole('heading',{name:'Временные признаки'})).toBeVisible()
 expect(screen.getByText('Через 1 день после поступления')).toBeVisible()
 expect(screen.getByText('Через 1–2 дня после поступления')).toBeVisible()
 expect(screen.getByText('2025-01-02 → 2025-01-03')).toBeVisible()
 expect(screen.getByText('Совпадение дат не доказывает, что переводились те же деньги.')).toBeVisible()
 expect(screen.getAllByText(/3 плательщика/)).toHaveLength(2)
 expect(screen.getByText(/Граница глубины 4/)).toBeVisible()
 expect(screen.getByRole('heading',{name:'Какие данные запросить дальше'})).toBeVisible()
 expect(screen.getByText(requests[0])).toBeVisible()
 expect(screen.getByText(requests[1])).toBeVisible()
})
test('older reports omit temporal sections and malformed optional evidence is nonfatal',async()=>{
 expect(parseReport(fixture).nodes[0].temporal).toBeUndefined()
 const invalid=parseReport({...fixture,nodes:[{...node,temporal:{incoming_tx_count:-1},next_data_requests:[' ',42]}]})
 expect(invalid.nodes[0].temporal).toBeUndefined()
 expect(invalid.nodes[0].next_data_requests).toEqual([])
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[{...node,temporal:{incoming_tx_count:-1},next_data_requests:[' ',42]}],top_nodes:[{rank:1,gid,role:'peripheral',priority_score:0.3,why:'Проверить'}]})}))
 render(<App />)
 expect(await screen.findByText('Часть дополнительных данных недоступна. Основные сведения об узле сохранены.')).toBeVisible()
 expect(screen.getByRole('heading',{name:`Узел ${gid}`})).toBeVisible()
 expect(screen.queryByRole('heading',{name:'Временные признаки'})).not.toBeInTheDocument()
})
test.each(['2025-01-02','2025-01-01','2025-01-05'])('optional date pair ending %s cannot claim a 1–2-day observation', outgoing_date=>{
 const parsed=parseReport({...fixture,nodes:[{...node,temporal:{after_1_or_2d_examples:[{incoming_date:'2025-01-02',outgoing_date}]}}]})
 expect(parsed.has_invalid_optional).toBe(true)
 expect(parsed.nodes[0].temporal?.after_1_or_2d_examples).toBeUndefined()
 expect(parsed.nodes[0].gid).toBe(gid)
})
test('contradictory optional counts and below-threshold peaks are hidden without losing the node',()=>{
 const parsed=parseReport({...fixture,nodes:[{...node,temporal:{incoming_tx_count:2,outgoing_tx_count:2,outgoing_after_1d_count:2,outgoing_after_1_or_2d_count:1,peak_day:{date:'2025-01-03',count:3,share:0.5,baseline_daily_count:2}}}]})
 expect(parsed.has_invalid_optional).toBe(true)
 expect(parsed.nodes[0].temporal?.outgoing_after_1d_count).toBeUndefined()
 expect(parsed.nodes[0].temporal?.outgoing_after_1_or_2d_count).toBeUndefined()
 expect(parsed.nodes[0].temporal?.peak_day).toBeUndefined()
 expect(parsed.nodes[0].evidence).toBe(node.evidence)
})
test('date evidence contradicting an explicit zero matched count is omitted',()=>{
 const parsed=parseReport({...fixture,nodes:[{...node,temporal:{outgoing_after_1_or_2d_count:0,after_1_or_2d_examples:[{incoming_date:'2025-01-02',outgoing_date:'2025-01-03'}]}}]})
 expect(parsed.has_invalid_optional).toBe(true)
 expect(parsed.nodes[0].temporal?.after_1_or_2d_examples).toBeUndefined()
})
test('exploration pages all report nodes and combines four labeled filters without narrowing gid search',async()=>{
 const nodes=Array.from({length:25},(_,i)=>({...node,gid:String(100+i),role:i%2?'transit':'peripheral',cluster_id:i%3,is_seed:i%4===0,boundary_censored:i%5===0,priority_score:i/100,evidence:`Узел ${i}`}))
 const clusters=[0,1,2].map(cluster_id=>({cluster_id,n_nodes:nodes.filter(n=>n.cluster_id===cluster_id).length,n_seed:2,sum_kzt_internal:100+cluster_id,top_gids:[],hypothesis:`Гипотеза ${cluster_id}`}))
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes,clusters,top_nodes:[]})}))
 render(<App />)
 expect(await screen.findByRole('heading',{name:'Исследование выборки'})).toBeVisible()
 expect(screen.getAllByRole('button',{name:/^Открыть узел \d+$/})).toHaveLength(20)
 expect(screen.getAllByRole('button',{name:/^Открыть узел \d+$/})[0]).toHaveAccessibleName('Открыть узел 124')
 expect(screen.getByText('Показано 20 из 25 узлов')).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:'Показать ещё'}))
 expect(screen.getAllByRole('button',{name:/^Открыть узел \d+$/})).toHaveLength(25)
 const choose=(label:string,option:string)=>{fireEvent.click(screen.getByRole('combobox',{name:label}));fireEvent.click(screen.getByRole('option',{name:option}))}
 choose('Роль','Транзит')
 choose('Кластер','Кластер 1')
 choose('Исходные узлы (seed)','Только исходные')
 choose('Граница выгрузки','Неграничные')
 expect(screen.getByText('По этим фильтрам узлы не найдены')).toBeVisible()
 fireEvent.change(screen.getByLabelText('Поиск по gid'),{target:{value:'100'}})
 fireEvent.click(screen.getByRole('button',{name:'Найти узел'}))
 expect(screen.getByRole('heading',{name:'Узел 100'})).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:'Сбросить фильтры'}))
 expect(screen.getByText('Показано 20 из 25 узлов')).toBeVisible()
})
test('cluster overview focuses results and member navigation uses the existing inspector',async()=>{
 const other={...node,gid:'222',cluster_id:1,role:'transit',evidence:'Участник второго кластера'}
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[node,other],clusters:[{cluster_id:0,n_nodes:1,n_seed:0,sum_kzt_internal:0,top_gids:[gid],hypothesis:'Первый кластер'},{cluster_id:1,n_nodes:1,n_seed:0,sum_kzt_internal:300,top_gids:[other.gid],hypothesis:'Второй кластер'}],top_nodes:[{rank:1,gid,role:'peripheral',priority_score:0.3,why:'Проверить'}]})}))
 render(<App />)
 fireEvent.click(await screen.findByRole('button',{name:'Вся выборка'}))
 fireEvent.click(screen.getByText(/Обзор кластеров/,{selector:'summary'}))
 fireEvent.click(await screen.findByRole('button',{name:'Исследовать кластер 1'}))
 expect(screen.getByRole('heading',{name:'Результаты исследования'})).toHaveFocus()
 expect(screen.getByText('в выборке: 1 узел',{exact:false})).toBeVisible()
 expect(screen.getByRole('combobox',{name:'Кластер'})).toHaveTextContent('Кластер 1')
 expect(screen.getByRole('heading',{name:`Узел ${gid}`})).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:'Открыть узел 222'}))
 expect(screen.getByRole('heading',{name:'Узел 222'})).toBeVisible()
 expect(screen.getByText('Участник второго кластера')).toBeVisible()
})
test('the priority workbench preserves twenty ranked rationales and opens any listed account',async()=>{
 const nodes=Array.from({length:20},(_,i)=>({...node,gid:String(700+i),evidence:`Наблюдение участника ${i}`}))
 const top_nodes=nodes.map((n,i)=>({rank:i+1,gid:n.gid,role:n.role,priority_score:1-i/100,why:`Основание для проверки ${i+1}`}))
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes,top_nodes,clusters:[]})}))
 render(<App />)
 await screen.findByRole('heading',{name:'Кого проверить первым'})
 expect(screen.getAllByRole('button',{name:/из рейтинга$/})).toHaveLength(20)
 for(const item of top_nodes){fireEvent.click(screen.getByRole('button',{name:`Открыть узел ${item.gid} из рейтинга`}));expect(screen.getByText(item.why)).toBeVisible()}
 fireEvent.click(screen.getByRole('button',{name:'Открыть узел 719 из рейтинга'}))
 expect(screen.getByRole('heading',{name:'Узел 719'})).toBeVisible()
 expect(screen.getByText('Наблюдение участника 19')).toBeVisible()
})

test('readable evidence preserves the exact source and links mobile flow to the current inspector', async () => {
 const evidence='Гипотеза coordinator: связь с 7 seed по путям; входов 9, выходов 25; посредничество 0.00847.'
 const why='Приоритет проверки 0.837: оборот 1513002.00 KZT; связей 34; путей от seed 7; посредничество 0.00847.'
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...fixture,nodes:[{...node,role:'coordinator',evidence}],top_nodes:[{rank:1,gid,role:'coordinator',priority_score:0.837,why}]})}))
 render(<App />)
 expect(await screen.findByText('Гипотеза «координация»: достижим из исходных узлов: 7; входов 9, выходов 25; посредничество 0.00847.')).toBeVisible()
 expect(screen.getByText(/исходных узлов с путём к участнику: 7/)).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:'Рабочая область'}))
 const link=screen.getByRole('link',{name:'Основание и данные участника ↓'})
 expect(link).toHaveAttribute('href','#participant-details')
 expect(document.getElementById('participant-details')).toHaveTextContent(`Узел ${gid}`)
 fireEvent.click(screen.getByText('Исходный текст расчёта',{selector:'summary'}))
 expect(screen.getByText(evidence)).toBeVisible()
 expect(screen.getByText(why)).toBeVisible()
})
