import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Network, Search, CircleAlert } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import Graph from './components/Graph'
import Inspector from './components/Inspector'
import { parseReport, roles, count, money, type Report } from './contract'
const gidOrder=(a:string,b:string)=>/^-?\d+$/.test(a)&&/^-?\d+$/.test(b)?(BigInt(a)<BigInt(b)?-1:BigInt(a)>BigInt(b)?1:0):a.localeCompare(b,'ru')
function FilterSelect({id,label,value,onChange,options}:{id:string;label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}) {
 return <div className="filter-field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{options.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>
}
export default function App() {
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[retry,setRetry]=useState(0),[searchMessage,setSearchMessage]=useState('')
 const [roleFilter,setRoleFilter]=useState('all'),[clusterFilter,setClusterFilter]=useState('all'),[seedFilter,setSeedFilter]=useState('all'),[boundaryFilter,setBoundaryFilter]=useState('all'),[visibleCount,setVisibleCount]=useState(20),[listMode,setListMode]=useState<'priority'|'all'>('priority')
 const resultsHeading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>{let ignore=false;const controller=new AbortController();setError('');setReport(null);fetch('/data/report.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(parseReport).then(r=>{if(!ignore){setReport(r);setSelected(r.top_nodes[0]?.gid??r.nodes[0]?.gid??'');if(!r.top_nodes.length)setListMode('all')}}).catch(e=>{if(!ignore)setError(String(e.message))});return()=>{ignore=true;controller.abort()}},[retry])
 const node=report?.nodes.find(n=>n.gid===selected)
 const select=(id:string)=>{setSelected(id);setSearchMessage('')}
 const search=()=>{const id=query.trim();if(!id){setSearchMessage('Введите gid, чтобы открыть узел и его связи.');return}if(report?.nodes.some(n=>n.gid===id)){select(id);setSearchMessage(`Открыт участник ${id}`)}else setSearchMessage('Узел не найден. Проверьте gid и повторите поиск.')}
 const updateFilter=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setVisibleCount(20)}
 const resetFilters=()=>{setRoleFilter('all');setClusterFilter('all');setSeedFilter('all');setBoundaryFilter('all');setVisibleCount(20)}
 const hasFilters=[roleFilter,clusterFilter,seedFilter,boundaryFilter].some(value=>value!=='all')
 const filtered=useMemo(()=>report?.nodes.filter(n=>(roleFilter==='all'||n.role===roleFilter)&&(clusterFilter==='all'||String(n.cluster_id)===clusterFilter)&&(seedFilter==='all'||n.is_seed===(seedFilter==='yes'))&&(boundaryFilter==='all'||n.boundary_censored===(boundaryFilter==='yes'))).sort((a,b)=>b.priority_score-a.priority_score||gidOrder(a.gid,b.gid))??[],[report,roleFilter,clusterFilter,seedFilter,boundaryFilter])
 const visible=filtered.slice(0,visibleCount)
 const investigateCluster=(id:number)=>{setClusterFilter(String(id));setVisibleCount(20);resultsHeading.current?.focus()}
 return <div className="app-shell"><header className="header"><div className="brand"><span className="brand-icon"><Network size={23}/></span><div><h1>Граф денег</h1><p>Рабочее место AML-аналитика</p></div></div><div className="header-actions"><span className="local-label"><i/> Локальный анализ</span><details className="header-menu"><summary>Как читать анализ</summary><div className="menu-content methodology"><h2>Как устроен анализ</h2><p>Данные → связи, суммы и даты → гипотезы ролей и кластеров → приоритеты проверки.</p><p>Приоритет 0–1 сравнивает структурные признаки участников. Это не вероятность виновности. Оценка роли показывает выраженность её правила.</p><p>Выборка ограничена одним банком, периодом и глубиной 4. Переводы ниже 5 000 KZT не видны. Входящие seed неполны; нулевые исходящие на границе не доказывают конечного получателя.</p>{report?.meta.warnings.map((w,i)=><p key={i}>{w}</p>)}</div></details><details className="header-menu"><summary className="export-trigger"><ArrowDownToLine size={16}/> Выгрузить CSV</summary><div className="menu-content downloads">{[['nodes_roles','роли'],['clusters','кластеры'],['top_nodes','приоритеты']].map(([file,label])=><Button key={file} variant="ghost" asChild><a href={`/data/${file}.csv`} download>Скачать {label} CSV <ArrowUpRight size={15}/></a></Button>)}</div></details></div></header>
 <main>{error?<Alert className="load-state" role="alert"><CircleAlert/><AlertDescription><h2>Не удалось загрузить результаты анализа.</h2><p>Проверьте, что локальный расчёт завершён, и повторите загрузку.</p><p>{error}</p><Button variant="outline" onClick={()=>setRetry(retry+1)}>Повторить загрузку</Button></AlertDescription></Alert>:!report?<div className="load-state" role="status"><p>Загружаем граф и результаты анализа…</p><div className="skeleton"/></div>:report.nodes.length===0?<div className="load-state"><h2>В выгрузке пока нет узлов</h2><p>Выполните локальный расчёт и обновите страницу.</p></div>:<>
 <div className="command-bar"><form className="search-form" onSubmit={e=>{e.preventDefault();search()}}><label className="sr-only" htmlFor="gid">Поиск по gid</label><div className="input-wrap"><Search size={17}/><Input id="gid" placeholder="Найти участника по gid" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)} aria-describedby="search-feedback"/></div><Button type="submit">Найти узел</Button></form><div className="dataset-meta"><strong>{count(report.nodes.length)} участников</strong><span>{count(report.edges.length)} связей</span><span>{count(report.meta.n_transactions)} переводов</span><span>{report.meta.period_start.slice(0,10)} — {report.meta.period_end.slice(0,10)}</span></div></div>
 <div className="context-bar"><p>Роли и приоритеты — гипотезы для проверки, не оценка виновности</p><p id="search-feedback" role="status">{searchMessage||'Поиск работает по всей выборке, включая изоляты'}</p></div>{report.has_invalid_optional&&<p className="optional-warning" role="status">Часть дополнительных данных недоступна. Основные сведения об узле сохранены.</p>}
 <div className="workbench"><aside className="investigation-panel"><div className="list-tabs"><Button variant={listMode==='priority'?'secondary':'ghost'} aria-pressed={listMode==='priority'} onClick={()=>setListMode('priority')}>Приоритеты <span>{report.top_nodes.length}</span></Button><Button variant={listMode==='all'?'secondary':'ghost'} aria-pressed={listMode==='all'} onClick={()=>setListMode('all')}>Вся выборка</Button></div>
 {listMode==='priority'?<><div className="list-intro"><h2>Кого проверить первым</h2><p>Выберите участника — справа появятся его связи и основание.</p></div><div className="priority-list" role="region" aria-label="Рейтинг участников" tabIndex={0}>{report.top_nodes.length?report.top_nodes.map(t=><button key={t.gid} className="priority-row" data-selected={selected===t.gid} aria-label={`Открыть узел ${t.gid} из рейтинга`} onClick={()=>select(t.gid)}><div className="priority-row-top"><span className="rank-number">{String(t.rank).padStart(2,'0')}</span><span className="priority-gid">{t.gid}</span><strong>{t.priority_score.toFixed(2)}</strong></div><div className="priority-role">{roles[t.role]}</div><p>{t.why}</p></button>):<p className="list-intro">Список приоритетов пуст. Найдите узел по gid, чтобы изучить его связи.</p>}</div></>:<><div className="list-intro"><h2>Исследование выборки</h2><p>Фильтры меняют список, поиск остаётся глобальным.</p></div><details className="filter-disclosure" open><summary>Фильтры {hasFilters&&'· применены'}</summary><div className="filter-grid"><FilterSelect id="role-filter" label="Роль" value={roleFilter} onChange={updateFilter(setRoleFilter)} options={[{value:'all',label:'Все'},...Object.entries(roles).map(([value,label])=>({value,label}))]}/><FilterSelect id="cluster-filter" label="Кластер" value={clusterFilter} onChange={updateFilter(setClusterFilter)} options={[{value:'all',label:'Все'},...report.clusters.map(c=>({value:String(c.cluster_id),label:`Кластер ${c.cluster_id}`}))]}/><FilterSelect id="seed-filter" label="Seed" value={seedFilter} onChange={updateFilter(setSeedFilter)} options={[{value:'all',label:'Все'},{value:'yes',label:'Только seed'},{value:'no',label:'Без seed'}]}/><FilterSelect id="boundary-filter" label="Граница выгрузки" value={boundaryFilter} onChange={updateFilter(setBoundaryFilter)} options={[{value:'all',label:'Все'},{value:'yes',label:'Граничные'},{value:'no',label:'Неграничные'}]}/></div>{hasFilters&&<Button variant="ghost" onClick={resetFilters}>Сбросить фильтры</Button>}</details>
 <details className="cluster-overview"><summary>Обзор кластеров · {report.clusters.length}</summary><div className="cluster-list">{report.clusters.map(c=><div className="cluster-row" key={c.cluster_id}><Button variant="ghost" onClick={()=>investigateCluster(c.cluster_id)} aria-label={`Исследовать кластер ${c.cluster_id}`}>Кластер {c.cluster_id}<ArrowUpRight size={14}/></Button><p>{count(c.n_nodes)} узлов · {count(c.n_seed)} seed</p><p>{money(c.sum_kzt_internal)} внутри</p><p>{c.hypothesis}</p></div>)}</div></details>
 <div className="results-heading"><h3 ref={resultsHeading} tabIndex={-1}>Результаты исследования</h3><p aria-live="polite"><span>Показано {visible.length} из {report.nodes.length} узлов</span><span> · в выборке: {filtered.length} {filtered.length===1?'узел':'узлов'}</span></p></div><div className="results-list" role="region" aria-label="Результаты исследования: узлы" tabIndex={0}>{!filtered.length?<div className="list-intro"><h3>По этим фильтрам узлы не найдены</h3><p>Измените условия или сбросьте фильтры.</p></div>:visible.map(n=><button key={n.gid} className="result-row" data-selected={selected===n.gid} aria-label={`Открыть узел ${n.gid}`} onClick={()=>select(n.gid)}><strong>{n.gid}</strong><span>{roles[n.role]} · {n.priority_score.toFixed(2)}</span><span>Кластер {n.cluster_id}{n.is_seed?' · Seed':''}{n.boundary_censored?' · Граница':''}</span></button>)}</div>{visible.length<filtered.length&&<Button variant="ghost" className="more-results" onClick={()=>setVisibleCount(v=>v+20)}>Показать ещё</Button>}</>}
 </aside><section className="graph-panel"><div className="panel-heading"><div><div className="eyebrow">СХЕМА ПЕРЕВОДОВ</div><h2>От кого и кому идут деньги</h2></div><span className="small muted">Один шаг от участника</span></div>{node?<Graph key={node.gid} report={report} selectedGid={node.gid} onSelect={select}/>:<p className="no-selection">Выберите участника в списке или найдите его по gid.</p>}</section>{node&&<Inspector key={node.gid} node={node} report={report} onSelect={select}/>}</div>
 <footer><p>{count(report.clusters.length)} кластеров · {count(report.meta.n_seed)} seed · {money(report.meta.total_kzt)} наблюдаемых переводов</p><span>Локальная выгрузка · исходные данные сохранены</span></footer><p className="sr-only" aria-live="polite">{node?`Выбран узел ${node.gid}`:''}</p></>}
 </main></div>
}
